"""把 sdlc-pipeline 以宿主原生方式安装到一个具体项目。

这不是 Codex/Claude/OpenCode 的全局插件安装器。它只写目标项目中的：
- 共享运行时：.sdlc-pipeline/
- Claude Code：.claude/skills、.claude/agents、.claude/settings.json
- Codex：.agents/skills、.codex/hooks.json
- OpenCode：.opencode/skills、.opencode/agents、.opencode/commands、
  .opencode/plugins
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import tempfile
from pathlib import Path


PLUGIN_ROOT = Path(__file__).resolve().parent.parent
VERSION = "0.4.0"
PHASES = ("init", "requirement", "design", "code", "test")
PROJECT_SKILLS = (*PHASES, "verify")
HOSTS = ("claude", "codex", "opencode")
RUNTIME_DIRS = ("scripts", "templates", "rules", "references", "agents")
MANAGED_MARKER = "Generated by sdlc-pipeline project installer."


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
        os.replace(tmp_name, path)
    finally:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass


def copy_runtime(target: Path) -> None:
    runtime = target / ".sdlc-pipeline"
    for name in RUNTIME_DIRS:
        source = PLUGIN_ROOT / name
        destination = runtime / name
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(
            source,
            destination,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
        )
    atomic_write(
        runtime / "installation.json",
        json.dumps(
            {
                "name": "sdlc-pipeline",
                "version": VERSION,
                "layout": "project-native",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )
    atomic_write(
        runtime / ".gitignore",
        "**/__pycache__/\n*.py[cod]\n",
    )


def rendered_skill(name: str, host: str) -> str:
    text = (PLUGIN_ROOT / "skills" / name / "SKILL.md").read_text(encoding="utf-8")
    text = text.replace(f"name: {name}", f"name: sdlc-pipeline-{name}", 1)
    text = text.replace("${CLAUDE_PLUGIN_ROOT}", ".sdlc-pipeline")
    text = text.replace(
        f"# /{name}", f"# sdlc-pipeline-{name}",
        1,
    )
    marker = (
        f"<!-- {MANAGED_MARKER} host={host}; source=skills/{name}/SKILL.md -->"
    )
    # Codex/OpenCode 都要求 YAML frontmatter 从文件第一个字节开始。
    closing = text.find("\n---", 4)
    if closing < 0:
        raise ValueError(f"skill 缺少 YAML frontmatter: {name}")
    insert_at = closing + len("\n---")
    return text[:insert_at] + f"\n\n{marker}" + text[insert_at:]


def install_skills(target: Path, host: str, root: Path) -> None:
    for phase in PROJECT_SKILLS:
        atomic_write(
            root / f"sdlc-pipeline-{phase}" / "SKILL.md",
            rendered_skill(phase, host),
        )


def rendered_hooks(host: str) -> dict:
    hooks = json.loads((PLUGIN_ROOT / "hooks" / "hooks.json").read_text(encoding="utf-8"))
    hooks["description"] = (
        f"sdlc-pipeline project-local hooks for {host}. {MANAGED_MARKER}"
    )
    for groups in hooks["hooks"].values():
        for group in groups:
            for handler in group.get("hooks", []):
                handler["command"] = handler["command"].replace(
                    "${CLAUDE_PLUGIN_ROOT}", ".sdlc-pipeline"
                )
                if host == "codex":
                    # Codex 从任意子目录启动时仍以项目根解析运行时。
                    handler["command"] = handler["command"].replace(
                        'python ".sdlc-pipeline/',
                        'python "$(git rev-parse --show-toplevel)/.sdlc-pipeline/',
                    )
                    handler["commandWindows"] = handler["command"].replace(
                        'python "$(git rev-parse --show-toplevel)/',
                        'python ".\\',
                    ).replace("/", "\\")
    return hooks


def install_claude(target: Path) -> None:
    install_skills(target, "claude", target / ".claude" / "skills")
    for role in ("coder", "tester"):
        source = (PLUGIN_ROOT / "agents" / f"{role}.md").read_text(encoding="utf-8")
        source = source.replace(f"name: {role}", f"name: sdlc-{role}", 1)
        atomic_write(
            target / ".claude" / "agents" / f"sdlc-{role}.md",
            f"<!-- {MANAGED_MARKER} -->\n" + source.replace("${CLAUDE_PLUGIN_ROOT}", ".sdlc-pipeline"),
        )

    settings_path = target / ".claude" / "settings.json"
    existing = {}
    if settings_path.exists():
        existing = json.loads(settings_path.read_text(encoding="utf-8"))
    generated = rendered_hooks("claude")["hooks"]
    hooks = existing.setdefault("hooks", {})
    for event, groups in generated.items():
        retained = [
            group
            for group in hooks.get(event, [])
            if not any(
                ".sdlc-pipeline" in handler.get("command", "")
                for handler in group.get("hooks", [])
            )
        ]
        hooks[event] = retained + groups
    atomic_write(settings_path, json.dumps(existing, ensure_ascii=False, indent=2) + "\n")


def install_codex(target: Path) -> None:
    install_skills(target, "codex", target / ".agents" / "skills")
    atomic_write(
        target / ".codex" / "hooks.json",
        json.dumps(rendered_hooks("codex"), ensure_ascii=False, indent=2) + "\n",
    )


def opencode_command(phase: str) -> str:
    description = (
        f"运行 SDLC Pipeline 的 {phase} 阶段"
        if phase in PHASES
        else "运行 SDLC Pipeline 的快速验证与可观测诊断"
    )
    return f"""---
description: {description}
---

使用 `sdlc-pipeline-{phase}` skill 执行当前项目的 {phase}。
先读取 skill 正文和其中列出的项目产物，不跳过门禁或交接证据。
"""


def opencode_agent(role: str) -> str:
    source = (PLUGIN_ROOT / "agents" / f"{role}.md").read_text(encoding="utf-8")
    body = re.sub(r"\A---\s*\n.*?\n---\s*\n", "", source, count=1, flags=re.DOTALL)
    body = body.replace("${CLAUDE_PLUGIN_ROOT}", ".sdlc-pipeline")
    description = (
        "实现 SDLC design 并返回可校验交接块"
        if role == "coder"
        else "只读走查 requirement/design/code 并返回双轴交接块"
    )
    permission = (
        "  edit: allow\n  bash: allow\n"
        if role == "coder"
        else "  edit: deny\n  bash: deny\n  task: deny\n"
    )
    return (
        "---\n"
        f"description: {description}\n"
        "mode: subagent\n"
        "permission:\n"
        f"{permission}"
        "---\n\n"
        f"<!-- {MANAGED_MARKER} -->\n"
        f"{body}"
    )


def install_opencode(target: Path) -> None:
    install_skills(target, "opencode", target / ".opencode" / "skills")
    for role in ("coder", "tester"):
        atomic_write(
            target / ".opencode" / "agents" / f"sdlc-{role}.md",
            opencode_agent(role),
        )
    for phase in PROJECT_SKILLS:
        atomic_write(
            target / ".opencode" / "commands" / f"sdlc-{phase}.md",
            opencode_command(phase),
        )
    plugin = (PLUGIN_ROOT / ".opencode" / "plugins" / "sdlc-pipeline.js").read_text(
        encoding="utf-8"
    )
    atomic_write(target / ".opencode" / "plugins" / "sdlc-pipeline.js", plugin)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="项目级安装 sdlc-pipeline")
    parser.add_argument("--target", required=True, help="目标项目根目录")
    parser.add_argument(
        "--host",
        action="append",
        choices=(*HOSTS, "all"),
        required=True,
        help="目标宿主；可重复，或使用 all",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="升级/重装受管文件；不会删除宿主目录中的非受管文件",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    target = Path(args.target).expanduser().resolve()
    if not target.is_dir():
        raise SystemExit(f"目标项目不存在或不是目录: {target}")
    marker = target / ".sdlc-pipeline" / "installation.json"
    if marker.exists() and not args.force:
        raise SystemExit("项目已安装 sdlc-pipeline；升级或重装请显式使用 --force")
    hosts = set(HOSTS if "all" in args.host else args.host)
    copy_runtime(target)
    if "claude" in hosts:
        install_claude(target)
    if "codex" in hosts:
        install_codex(target)
    if "opencode" in hosts:
        install_opencode(target)
    installation = json.loads(marker.read_text(encoding="utf-8"))
    installation["hosts"] = sorted(hosts)
    atomic_write(marker, json.dumps(installation, ensure_ascii=False, indent=2) + "\n")
    print(
        json.dumps(
            {
                "ok": True,
                "target": str(target),
                "hosts": sorted(hosts),
                "runtime": str(target / ".sdlc-pipeline"),
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
