/**
 * 亿联中控 HttpApi 错误码（参考 HTTPS_API.md 第 3 页错误码表）
 */
export const ERROR_CODE = {
  UNKNOWN: 10001,
  NOT_SUPPORT: 10002,
  INVALID_PARAM: 10003,
  BUSY: 10004,
  FILE_GEN_FAIL: 10005,
  PERMISSION_DENIED: 10006,
  PASSWORD_INCORRECT: 10007,
  REFRESH_TOKEN_FAIL: 10008,
  AUTHENTICATION_REQUIRED: 10009,
  EXCEED_MAX_CONCURRENCY: 10010,
  TASK_PROCESS_NOT_EXIST: 10011,
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export const ERROR_CODE_TO_MESSAGE: Record<ErrorCode, string> = {
  [ERROR_CODE.UNKNOWN]: '未知错误',
  [ERROR_CODE.NOT_SUPPORT]: '设备不支持该操作',
  [ERROR_CODE.INVALID_PARAM]: '参数错误',
  [ERROR_CODE.BUSY]: '设备繁忙（通话中）',
  [ERROR_CODE.FILE_GEN_FAIL]: '文件生成失败',
  [ERROR_CODE.PERMISSION_DENIED]: '权限不足',
  [ERROR_CODE.PASSWORD_INCORRECT]: '设备 admin 密码错误',
  [ERROR_CODE.REFRESH_TOKEN_FAIL]: '刷新 token 失败',
  [ERROR_CODE.AUTHENTICATION_REQUIRED]: '鉴权失败，请重新登录',
  [ERROR_CODE.EXCEED_MAX_CONCURRENCY]: '请求过于频繁，请稍候',
  [ERROR_CODE.TASK_PROCESS_NOT_EXIST]: '任务进程不存在',
};
